#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/arc_hunyuan_video/modular_arc_hunyuan_video.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_arc_hunyuan_video.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
from ...configuration_utils import PretrainedConfig


class ARCHunyuanVideoAudioConfig(PretrainedConfig):
    model_type = "arc_hunyuan_video_audio"

    def __init__(
        self,
        vocab_size=51865,
        num_mel_bins=80,
        encoder_layers=4,
        encoder_attention_heads=6,
        decoder_layers=4,
        decoder_attention_heads=6,
        decoder_ffn_dim=1536,
        encoder_ffn_dim=1536,
        encoder_layerdrop=0.0,
        decoder_layerdrop=0.0,
        decoder_start_token_id=50257,
        use_cache=True,
        is_encoder_decoder=True,
        activation_function="gelu",
        d_model=384,
        dropout=0.0,
        attention_dropout=0.0,
        activation_dropout=0.0,
        init_std=0.02,
        scale_embedding=False,
        max_source_positions=1500,
        max_target_positions=448,
        pad_token_id=50256,
        bos_token_id=50256,
        eos_token_id=50256,
        suppress_tokens=None,
        begin_suppress_tokens=[220, 50256],
        use_weighted_layer_sum=False,
        classifier_proj_size=256,
        apply_spec_augment=False,
        mask_time_prob=0.05,
        mask_time_length=10,
        mask_time_min_masks=2,
        mask_feature_prob=0.0,
        mask_feature_length=10,
        mask_feature_min_masks=0,
        median_filter_width=7,
        **kwargs,
    ):
        self.vocab_size = vocab_size
        self.num_mel_bins = num_mel_bins
        self.d_model = d_model
        self.encoder_layers = encoder_layers
        self.encoder_attention_heads = encoder_attention_heads
        self.decoder_layers = decoder_layers
        self.decoder_attention_heads = decoder_attention_heads
        self.decoder_ffn_dim = decoder_ffn_dim
        self.encoder_ffn_dim = encoder_ffn_dim
        self.dropout = dropout
        self.attention_dropout = attention_dropout
        self.activation_dropout = activation_dropout
        self.activation_function = activation_function
        self.init_std = init_std
        self.encoder_layerdrop = encoder_layerdrop
        self.decoder_layerdrop = decoder_layerdrop
        self.use_cache = use_cache
        self.num_hidden_layers = encoder_layers
        self.scale_embedding = scale_embedding  # scale factor will be sqrt(d_model) if True
        self.max_source_positions = max_source_positions
        self.max_target_positions = max_target_positions

        # Audio Classification-specific parameters. Feel free to ignore for other classes.
        self.classifier_proj_size = classifier_proj_size
        self.use_weighted_layer_sum = use_weighted_layer_sum

        # fine-tuning config parameters for SpecAugment: https://huggingface.co/papers/1904.08779
        self.apply_spec_augment = apply_spec_augment
        self.mask_time_prob = mask_time_prob
        self.mask_time_length = mask_time_length
        self.mask_time_min_masks = mask_time_min_masks
        self.mask_feature_prob = mask_feature_prob
        self.mask_feature_length = mask_feature_length
        self.mask_feature_min_masks = mask_feature_min_masks

        self.median_filter_width = median_filter_width

        super().__init__(
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            is_encoder_decoder=is_encoder_decoder,
            decoder_start_token_id=decoder_start_token_id,
            suppress_tokens=suppress_tokens,
            begin_suppress_tokens=begin_suppress_tokens,
            **kwargs,
        )


class ARCHunyuanVideoVisionConfig(PretrainedConfig):
    model_type = "arc_hunyuan_video_vision"

    def __init__(
        self,
        hidden_size=1152,
        intermediate_size=4304,
        num_hidden_layers=27,
        num_attention_heads=16,
        hidden_act="gelu",
        layer_norm_eps=1e-5,
        attention_dropout=0.0,
        patch_size=16,
        num_channels=3,
        max_image_size=2048,
        max_vit_seq_len=1600,
        anyres_pooling_size=2,
        force_image_size=640,
        attention_bias=True,
        mlp_bias=True,
        use_qk_norm=False,
        use_rotary_pos_emb=False,
        is_causal=False,
        num_key_value_heads=None,
        attention_head_dim=None,
        rms_norm_eps=1e-5,
        norm_type="torch_nn",
        position_embedding_xdrope=False,
        xdrope_section=None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.hidden_act = hidden_act
        self.layer_norm_eps = layer_norm_eps
        self.attention_dropout = attention_dropout
        self.patch_size = patch_size
        self.num_channels = num_channels
        self.max_image_size = max_image_size
        self.max_vit_seq_len = max_vit_seq_len
        self.anyres_pooling_size = anyres_pooling_size
        self.force_image_size = force_image_size
        self.attention_bias = attention_bias
        self.mlp_bias = mlp_bias
        self.use_qk_norm = use_qk_norm
        self.use_rotary_pos_emb = use_rotary_pos_emb
        self.is_causal = is_causal
        self.num_key_value_heads = num_key_value_heads if num_key_value_heads is not None else num_attention_heads
        self.attention_head_dim = (
            attention_head_dim if attention_head_dim is not None else hidden_size // num_attention_heads
        )
        self.rms_norm_eps = rms_norm_eps
        self.norm_type = norm_type
        self.position_embedding_xdrope = position_embedding_xdrope
        self.xdrope_section = xdrope_section


class ARCHunyuanVideoTextConfig(PretrainedConfig):
    model_type = "arc_hunyuan_video_text"

    def __init__(
        self,
        vocab_size=128256,
        hidden_size=4096,
        intermediate_size=14336,
        num_hidden_layers=32,
        num_attention_heads=32,
        num_key_value_heads=8,
        hidden_act="silu",
        max_position_embeddings=1024,
        initializer_range=0.02,
        rms_norm_eps=1e-5,
        use_cache=True,
        pad_token_id=0,
        bos_token_id=1,
        eos_token_id=2,
        tie_word_embeddings=True,
        rope_theta=10000.0,
        rope_scaling=None,
        attention_bias=False,
        mlp_bias=False,
        attention_dropout=0.0,
        use_qk_norm=True,
        use_rotary_pos_emb=True,
        norm_type="hf_rms",
        num_media_embeds=257,
        eod_token_id=3,
        im_start_id=127962,
        im_end_id=127963,
        image_token_id=127968,
        im_newline_id=127999,
        position_embedding_xdrope=True,
        xdrope_section=None,
        is_causal=True,
        attention_head_dim=None,
        **kwargs,
    ):
        super().__init__(
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )
        self.vocab_size = vocab_size
        self.max_position_embeddings = max_position_embeddings
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.num_key_value_heads = num_key_value_heads
        self.hidden_act = hidden_act
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.use_cache = use_cache
        self.rope_theta = rope_theta
        self.rope_scaling = rope_scaling
        self.attention_bias = attention_bias
        self.mlp_bias = mlp_bias
        self.attention_dropout = attention_dropout
        self.use_qk_norm = use_qk_norm
        self.use_rotary_pos_emb = use_rotary_pos_emb
        self.norm_type = norm_type
        self.num_media_embeds = num_media_embeds
        self.eod_token_id = eod_token_id
        self.im_start_id = im_start_id
        self.im_end_id = im_end_id
        self.image_token_id = image_token_id
        self.im_newline_id = im_newline_id
        self.position_embedding_xdrope = position_embedding_xdrope
        self.xdrope_section = xdrope_section
        self.is_causal = is_causal
        self.attention_head_dim = (
            attention_head_dim if attention_head_dim is not None else hidden_size // num_attention_heads
        )


class ARCHunyuanVideoConfig(PretrainedConfig):
    model_type = "arc_hunyuan_video"
    sub_configs = {
        "text_config": ARCHunyuanVideoTextConfig,
        "vision_config": ARCHunyuanVideoVisionConfig,
        "audio_config": ARCHunyuanVideoAudioConfig,
    }

    def __init__(self, text_config=None, vision_config=None, audio_config=None, **kwargs):
        super().__init__(**kwargs)

        if text_config is None:
            text_config = {}
        if vision_config is None:
            vision_config = {}
        if audio_config is None:
            audio_config = {}

        self.text_config = ARCHunyuanVideoTextConfig(**text_config)
        self.vision_config = ARCHunyuanVideoVisionConfig(**vision_config)
        self.audio_config = ARCHunyuanVideoAudioConfig(**audio_config)


__all__ = [
    "ARCHunyuanVideoConfig",
    "ARCHunyuanVideoVisionConfig",
    "ARCHunyuanVideoAudioConfig",
    "ARCHunyuanVideoTextConfig",
]
